Faster start time after initial start

diff --git a/ldap/ldap-entrypoint b/ldap/ldap-entrypoint
--- a/ldap/ldap-entrypoint
+++ b/ldap/ldap-entrypoint
@@ -1,15 +1,22 @@
 #! /bin/bash
 
-/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
-status=$?
-if [ $status -ne 0 ]; then
-  echo "Failed to start LDAP: $status"
-  exit $status
+if [ ! -f /zimbra/configured ]; then
+    echo "Configuring LDAP"
+    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo "Failed to configure LDAP: $status"
+      exit $status
+    fi
+
+    touch /zimbra/configured
 fi
+
+sudo -u zimbra /opt/zimbra/bin/zmcontrol start
 
 # TODO: not sure if this is necessary
 su -c /opt/zimbra/bin/zmupdateauthkeys zimbra
 
 # start simple healthcheck so other nodes in the cluster can coordinate startup
 echo "LDAP started"
-/opt/zimbra/healthcheck.py
+/zimbra/healthcheck.py
diff --git a/mailbox/mailbox-entrypoint b/mailbox/mailbox-entrypoint
--- a/mailbox/mailbox-entrypoint
+++ b/mailbox/mailbox-entrypoint
@@ -9,12 +9,21 @@ while [ $status -ne 200 ]; do
 done
 echo "MTA available"
 
-/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
-status=$?
-if [ $status -ne 0 ]; then
-  echo "Failed to start MAILBOX: $status"
-  exit $status
+if [ ! -f /zimbra/configured ]; then
+    echo "Setting MAILBOX configuration..."
+
+    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo "Failed to configure MAILBOX: $status"
+      exit $status
+    fi
+
+    touch /zimbra/configured
 fi
+
+echo "Starting MAILBOX"
+sudo -u zimbra /opt/zimbra/bin/zmcontrol start
 
 # TODO: not sure if this is necessary
 su -c /opt/zimbra/bin/zmupdateauthkeys zimbra
diff --git a/mta/mta-entrypoint b/mta/mta-entrypoint
--- a/mta/mta-entrypoint
+++ b/mta/mta-entrypoint
@@ -9,12 +9,19 @@ while [ $status -ne 200 ]; do
 done
 echo "LDAP available"
 
-/opt/zimbra/libexec/zmsetup.pl -c /tmp/config
-status=$?
-if [ $status -ne 0 ]; then
-  echo "Failed to start MTA: $status"
-  exit $status
+if [ ! -f /zimbra/configured ]; then
+    echo "Configuring MTA"
+    /opt/zimbra/libexec/zmsetup.pl -c /tmp/config
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo "Failed to configure MTA: $status"
+      exit $status
+    fi
+
+    touch /zimbra/configured
 fi
+
+sudo -u zimbra /opt/zimbra/bin/zmcontrol start
 
 # TODO: not sure if this is necessary
 su -c /opt/zimbra/bin/zmupdateauthkeys zimbra
